dist: xenial
language: clojure
services: 
  - xvfb
install: yarn install && npx shadow-cljs compile test-karma
script: npx karma start --single-run
sudo: true
cache:
  directories:
  - $HOME/.m2
  - .shadow-cljs
